"""empty message

Revision ID: 87767fc08bb4
Revises: 7e907e74a3b2
Create Date: 2024-02-13 17:15:58.228955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87767fc08bb4'
down_revision = '7e907e74a3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
